name: Contribution to the developer forum
description: File a developer forum contribution request
title: "[Developer Forum]: REPLACE ME WITH YOUR TOPIC FOR THE DEVELOPER FORUM"
labels: [developerforum]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        If you would like to presetn something on the developer forum, please submit this form.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: topin-description
    attributes:
      label: Description
      description: Write a brief description of your topic for the developer forum.
      placeholder: Tell us your topic description!
      value: "It introduces Bioconductor-related XXX."
    validations:
      required: true
