name: Request to add Bioconductor event calendar 
description: File a event calendar request
title: "[Event]: REPLACE ME WITH YOUR EVENT TITLE"
labels: [event, calendar]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        (As of June 2021, "events" are assumed to be "virtual events" only.)
        Submit this form and your event will be listed on the bioconductor.org calendar.
        Please review the following minimum requirements before submitting this form:
        
          1. Having a Bioconductor focus or be of interest to Bioconductor users/developers
          2. The event organizer will read and confirm the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/)
        
        Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
