name: Request to add your event to Bioconductor event calendar
description: File a event calendar request
title: "[Event]: REPLACE ME WITH YOUR EVENT NAME"
labels: [event, calendar]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        Submit this form and your event will be listed on the bioconductor.org calendar.
        Please review the following minimum requirements before submitting this form:
        
          1. Having a Bioconductor focus or be of interest to Bioconductor users/developers.
          2. The event organizer should (read and) confirm the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          3. The event organizer should specify a Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          4. The event organizer should summarise the CoC. (The event participants might not have time to read the CoC in a busy class, so it is good to take some time out.)
        
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: event-type
    attributes:
      label: Type
      description: Write a type of your event.
      placeholder: Tell us your event type!
      value: "workshop, hack-a-thon, meetup, lecture, etc"
    validations:
      required: true
  - type: textarea
    id: event-description
    attributes:
      label: Description
      description: Write a brief description of your event.
      placeholder: Tell us your event description!
      value: "It involves ..."
    validations:
      required: true
  - type: textarea
    id: whereis
    attributes:
      label: Where is your event located?
      description: Also tell us your event location and time-zone + if it is virtual or not.
      placeholder: Tell us your event location and time-zone + if it is virtual or not.
    validations:
      required: true
  - type: textarea
    id: event-website
    attributes:
      label: Website
      description: Write a website of your event.
      placeholder: Tell us your event website!
      value: "https://eventwebsite.com"
    validations:
      required: true
  - type: dropdown
    id: repeatingORoneoff
    attributes:
      label: Repeating or one-off events?
      description: Select either
      options:
        - Repeating
        - One-off
      default: 0
    validations:
      required: true

  - type: dropdown
    id: gcalrepeatingdate1
    attributes:
      label: If you selected "Repeating", select below. If you selected "One-off", skip this.
      description: How does your event repeat?
      options:
        - Repeat every ___ , Repeat on ___ , Ends on ___ / Ends after ___ occurrences
        - Monthly on ___th
        - Weekly on ___day
      default: 0
    validations:
      required: false
  - type: textarea
    id: gcalrepeatingdate2
    attributes:
      label: If you selected "Repeating", select below also. If you selected "One-off", skip this.
      description: Add the information where it says ___ in the previous option.
      placeholder: For example, Repeat every Month, Repeat on the third Friday, Ends after 3 occurrences
    validations:
      required: false
  - type: textarea
    id: gcalrepetingtime
    attributes:
      label: If you selected "Repeating", specify the time at which the repeats occur. If you selected "One-off", skip this.
      description: Specify the time.
      placeholder: 5:00PM-6:00PM
    validations:
      required: false
  - type: textarea
    id: othertype
    attributes:
      label: If you selected "One-off" or your event repeats in a manner other than the Google Calendar support types above,
      description: Specify a date and time or a list of dates and times.
      placeholder: Apr 4, May 5 5:00PM-6:00PM, Jun 6 6PM-6PM, Jul 7 7PM-7PM, Aug 8 8PM-8
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: This field (email address) is not always required. Please write if you don't mind revealing your email address. If we need to contact you privately, we will contact you at the email address.
      placeholder: ex. email@example.com      
  - type: textarea
    id: registration-details
    attributes:
      label: Registration details (if applicable)
      description: Write registration details of your event (if applicable).
      placeholder: Tell us your event registration details! (if applicable).
      value: "Registration details"
  - type: textarea
    id: sponsor-organization
    attributes:
      label: Sponsor or Organization
      description: Sponsor or Organization
      placeholder: Let us know if there is a sponsor or organization
      value: "Sponsor or organization"      
  - type: textarea
    id: comment
    attributes:
      label: Comment field
      description: Please let us know if there is anything else. For example, the above events are repeated regularly.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: This event has a Bioconductor focus or interest to Bioconductor users/developers.
          required: true
        - label: The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event organizer have the shorter version (summary) of the CoC.
          required: true
          
