name: Request to add your event to Bioconductor event calendar
description: File a event calendar request
title: "[Event]: REPLACE ME WITH YOUR EVENT TITLE"
labels: [event, calendar]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        (As of June 2021, "events" are assumed to be "virtual events" only.)
        Submit this form and your event will be listed on the bioconductor.org calendar.
        Please review the following minimum requirements before submitting this form:
        
          1. Having a Bioconductor focus or be of interest to Bioconductor users/developers.
          2. The event organizer should (read and) confirm the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          3. The event organizer should specify a Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          4. The event organizer should summarise the CoC. (The event participants might not have time to read the CoC in a busy class, so it is good to take some time out.)
        
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: event-name
    attributes:
      label: Name
      description: Write a name of your event.
      placeholder: Tell us your event name!
      value: "event name"
    validations:
      required: true
  - type: textarea
    id: event-type
    attributes:
      label: Type
      description: Write a type of your event.
      placeholder: Tell us your event type!
      value: "workshop, hack-a-thon, meetup, lecture, etc"
    validations:
      required: true
  - type: textarea
    id: event-description
    attributes:
      label: Description
      description: Write a brief description of your event.
      placeholder: Tell us your event description!
      value: "It involves Bioconductor-centric workshops. It is organized by XXX."
    validations:
      required: true
  - type: textarea
    id: event-location
    attributes:
      label: Location
      description: Write a location of your event.
      placeholder: Tell us your event location!
      value: "event location"
    validations:
      required: true
  - type: textarea
    id: event-website
    attributes:
      label: Website
      description: Write a website of your event.
      placeholder: Tell us your event website!
      value: "https://eventwebsite.com"
    validations:
      required: true
  - type: textarea
    id: registration-details
    attributes:
      label: Registration details (if applicable)
      description: Write registration details of your event (if applicable).
      placeholder: Tell us your event registration details! (if applicable).
      value: "Registration details"
  - type: textarea
    id: sponsor-organization
    attributes:
      label: Sponsor or Organization
      description: Sponsor or Organization
      placeholder: Let us know if there is a sponsor or organization
      value: "Sponsor or organization"
  - type: textarea
    id: startdatetime
    attributes:
      label: Start date and time
      description: When does the event start?
    validations:
      required: true
  - type: textarea
    id: enddatetime
    attributes:
      label: End date and time
      description: When does the event end?
    validations:
      required: true
  - type: textarea
    id: timezone
    attributes:
      label: Time zone
      description: What is the time zone for the event date and time?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: This field (email address) is not always required. Please write if you don't mind revealing your email address. If we need to contact you privately, we will contact you at the email address.
      placeholder: ex. email@example.com
  - type: textarea
    id: comment
    attributes:
      label: Comment field
      description: Please let us know if there is anything else. For example, the above events are repeated regularly.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: This event has a Bioconductor focus or interest to Bioconductor users/developers.
          required: true
        - label: The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event organizer have the shorter version (summary) of the CoC.
          required: true
          
