name: Repeating Event Submission
description: File a repeating event submission.
title: "[Repeating Event]: REPLACE ME WITH YOUR EVENT NAME"
labels: ["repeatingevent", "calendar"]
assignees:
  - kozo2
body:
  - type: textarea
    id: whereis
    attributes:
      label: Where is your event located?
      description: Also tell us if it is virtual or not.
      placeholder: Tell us where we meet!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
