name: Repeating Event Submission
description: File a repeating event submission.
title: "[Repeating Event]: REPLACE ME WITH YOUR EVENT NAME"
labels: ["repeatingevent", "calendar"]
assignees:
  - kozo2
body:
  - type: textarea
    id: whereis
    attributes:
      label: Where is your event located?
      description: Also tell us if it is virtual or not.
      placeholder: Tell us where we meet!
    validations:
      required: true
  - type: dropdown
    id: gcalrepeating1
    attributes:
      label: The types of your repeating (that Google Calendar supports) step1
      description: How does your event repeat?
      options:
        - Repeat every ___ , Repeat on ___ , Ends on ___ / Ends after ___ occurrences
        - Monthly on ___th
        - Weekly on ___day
      default: 0
    validations:
      required: false
  - type: textarea
    id: gcalrepeating2
    attributes:
      label: The types of your repeating (that Google Calendar supports) step2
      description: Add the information where it says ___ in the previous option.
      placeholder: For example, Repeat every Month, Repeat on the third Friday, Ends after 3 occurrences
    validations:
      required: false
