name: Request to add your video to Bioconductor YouTube channel
description: File a YouTube video contribution request
title: "[Youtube]: REPLACE ME WITH YOUR YOUTUBE VIDEO TITLE"
labels: [youtube]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        If you would like to add your video to [Bioconductor YouTube channel](https://www.youtube.com/user/bioconductor), please submit this form.
        There are the minimum requirements for the submission.
        Please review the following minimum requirements before submitting this form:
        
          1. Having a Bioconductor focus or be of interest to Bioconductor users/developers.
          2. The video should comply with [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
        
        Thanks for taking the time to fill out this form!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: video-description
    attributes:
      label: Description
      description: Write a brief description of your video.
      placeholder: Tell us your video description!
      value: "It introduces Bioconductor-related XXX."
    validations:
      required: true
  - type: textarea
    id: video-storage
    attributes:
      label: Network storage where video is located
      description: Where can we get your video?
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Comment field
      description: Please let us know if there is anything else.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: This video has a Bioconductor focus or interest to Bioconductor users/developers.
          required: true
        - label: The video complies with [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
